spring:
  application:
    name: Sistema de Controle de Notas

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SCN?ApplicationName=SistemaDeControleDeNotas
    username: postgres
    password: admin

  hikari:
    maximumPoolSize: 3
    minimumIdle: 2
    idleTimeout: 20000
    poolName: SistemaDeControleDeNotaspool

